apiVersion: labservices.azure.upbound.io/v1beta2
kind: LabServiceLab
metadata:
  annotations:
    meta.upbound.io/example-id: labservices/v1beta2/labservicelab
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    security:
    - openAccessEnabled: false
    title: Test Title
    virtualMachine:
    - adminUser:
      - passwordSecretRef:
          key: example-key
          name: example-secret
          namespace: upbound-system
        username: testadmin
      imageReference:
      - offer: 0001-com-ubuntu-server-jammy
        publisher: Canonical
        sku: 22_04-lts
        version: latest
      sku:
      - capacity: 0
        name: Classic_Fsv2_2_4GB_128_S_SSD

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: labservices/v1beta2/labservicelab
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
