apiVersion: network.azure.upbound.io/v1beta1
kind: ExpressRouteCircuitAuthorization
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/expressroutecircuitauthorization
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    expressRouteCircuitNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: network.azure.upbound.io/v1beta2
kind: ExpressRouteCircuit
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/expressroutecircuitauthorization
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    allowClassicOperations: false
    bandwidthInMbps: 50
    location: West Europe
    peeringLocation: Silicon Valley
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serviceProviderName: Equinix
    sku:
    - family: MeteredData
      tier: Standard
    tags:
      environment: Production

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/expressroutecircuitauthorization
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
