apiVersion: network.azure.upbound.io/v1beta1
kind: SubnetServiceEndpointStoragePolicy
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/subnetserviceendpointstoragepolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    definition:
    - description: definition1
      name: name1
      service: Microsoft.Storage
      serviceResources:
      - ${azurerm_resource_group.example.id}
      - ${azurerm_storage_account.example.id}
    - description: definition2
      name: name2
      service: Global
      serviceResources:
      - /services/Azure
      - /services/Azure/Batch
      - /services/Azure/DataFactory
      - /services/Azure/MachineLearning
      - /services/Azure/ManagedInstance
      - /services/Azure/WebPI
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/subnetserviceendpointstoragepolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: storage.azure.upbound.io/v1beta2
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/subnetserviceendpointstoragepolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountReplicationType: GRS
    accountTier: Standard
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
