apiVersion: netapp.azure.upbound.io/v1beta2
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: netapp/v1beta2/account
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    activeDirectory:
    - dnsServers:
      - 1.2.3.4
      domain: westcentralus.com
      organizationalUnit: OU=FirstLevel
      passwordSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      smbServerName: SMBSERVER
      username: aduser
    identity:
    - identityIds:
      - ${azurerm_user_assigned_identity.example.id}
      type: UserAssigned
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: netapp/v1beta2/account
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: managedidentity.azure.upbound.io/v1beta1
kind: UserAssignedIdentity
metadata:
  annotations:
    meta.upbound.io/example-id: netapp/v1beta2/account
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    name: anf-user-assigned-identity
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
