apiVersion: eventhub.azure.upbound.io/v1beta2
kind: EventHubNamespace
metadata:
  annotations:
    meta.upbound.io/example-id: eventhub/v1beta2/eventhubnamespace
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    capacity: 2
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sku: Standard
    tags:
      environment: Production

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: eventhub/v1beta2/eventhubnamespace
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
