apiVersion: network.azure.upbound.io/v1beta2
kind: ExpressRoutePort
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta2/expressrouteport
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bandwidthInGbps: 10
    encapsulation: Dot1Q
    location: West Europe
    peeringLocation: Airtel-Chennai-CLS
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta2/expressrouteport
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West US
