apiVersion: network.azure.upbound.io/v1beta2
kind: LocalNetworkGateway
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta2/localnetworkgateway
  labels:
    testing.upbound.io/example-name: home
  name: home
spec:
  forProvider:
    addressSpace:
    - 10.0.0.0/16
    gatewayAddress: 12.13.14.15
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta2/localnetworkgateway
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
