apiVersion: dataprotection.azure.upbound.io/v1beta1
kind: BackupPolicyBlobStorage
metadata:
  annotations:
    meta.upbound.io/example-id: dataprotection/v1beta1/backuppolicyblobstorage
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    retentionDuration: P30D
    vaultIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: dataprotection.azure.upbound.io/v1beta2
kind: BackupVault
metadata:
  annotations:
    meta.upbound.io/example-id: dataprotection/v1beta1/backuppolicyblobstorage
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    datastoreType: VaultStore
    location: West Europe
    redundancy: LocallyRedundant
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dataprotection/v1beta1/backuppolicyblobstorage
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
