apiVersion: media.azure.upbound.io/v1beta1
kind: StreamingLocator
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta1/streaminglocator
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    assetNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    filterNames:
    - ${azurerm_media_services_account_filter.example.name}
    mediaServicesAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    streamingPolicyName: Predefined_ClearStreamingOnly

---

apiVersion: media.azure.upbound.io/v1beta1
kind: Asset
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta1/streaminglocator
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Asset description
    mediaServicesAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: media.azure.upbound.io/v1beta2
kind: ServicesAccount
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta1/streaminglocator
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    storageAccount:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      isPrimary: true

---

apiVersion: media.azure.upbound.io/v1beta2
kind: ServicesAccountFilter
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta1/streaminglocator
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    mediaServicesAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta1/streaminglocator
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: storage.azure.upbound.io/v1beta2
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta1/streaminglocator
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountReplicationType: GRS
    accountTier: Standard
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
