apiVersion: datafactory.azure.upbound.io/v1beta2
kind: LinkedServiceOdbc
metadata:
  annotations:
    meta.upbound.io/example-id: datafactory/v1beta2/linkedserviceodbc
  labels:
    testing.upbound.io/example-name: anonymous
  name: anonymous
spec:
  forProvider:
    connectionString: Driver={SQL Server};Server=test;Database=test;Uid=test;Pwd=test;
    dataFactoryIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: datafactory.azure.upbound.io/v1beta2
kind: Factory
metadata:
  annotations:
    meta.upbound.io/example-id: datafactory/v1beta2/linkedserviceodbc
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: datafactory/v1beta2/linkedserviceodbc
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
