apiVersion: insights.azure.upbound.io/v1beta2
kind: ApplicationInsightsStandardWebTest
metadata:
  annotations:
    meta.upbound.io/example-id: insights/v1beta2/applicationinsightsstandardwebtest
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applicationInsightsIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    geoLocations:
    - example
    location: West Europe
    request:
    - url: http://www.example.com
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: insights.azure.upbound.io/v1beta1
kind: ApplicationInsights
metadata:
  annotations:
    meta.upbound.io/example-id: insights/v1beta2/applicationinsightsstandardwebtest
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applicationType: web
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: insights/v1beta2/applicationinsightsstandardwebtest
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
