apiVersion: media.azure.upbound.io/v1beta2
kind: LiveEvent
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta2/liveevent
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: My Event Description
    encoding:
    - keyFrameInterval: PT2S
      presetName: Default720p
      stretchMode: AutoFit
      type: Standard
    hostnamePrefix: special-event
    input:
    - ipAccessControlAllow:
      - address: 0.0.0.0
        name: AllowAll
        subnetPrefixLength: 0
      streamingProtocol: RTMP
    location: West Europe
    mediaServicesAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    preview:
    - ipAccessControlAllow:
      - address: 0.0.0.0
        name: AllowAll
        subnetPrefixLength: 0
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    streamOptions:
    - LowLatency
    transcriptionLanguages:
    - en-US
    useStaticHostname: true

---

apiVersion: media.azure.upbound.io/v1beta2
kind: ServicesAccount
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta2/liveevent
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    storageAccount:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      isPrimary: true

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta2/liveevent
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: storage.azure.upbound.io/v1beta2
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta2/liveevent
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountReplicationType: GRS
    accountTier: Standard
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
