apiVersion: media.azure.upbound.io/v1beta2
kind: ServicesAccountFilter
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta2/servicesaccountfilter
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    firstQualityBitrate: 128000
    mediaServicesAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    presentationTimeRange:
    - endInUnits: 15
      forceEnd: false
      liveBackoffInUnits: 0
      presentationWindowInUnits: 90
      startInUnits: 0
      unitTimescaleInMilliseconds: 1000
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    trackSelection:
    - condition:
      - operation: Equal
        property: Type
        value: Audio
      - operation: NotEqual
        property: Language
        value: en
      - operation: NotEqual
        property: FourCC
        value: EC-3
    - condition:
      - operation: Equal
        property: Type
        value: Video
      - operation: Equal
        property: Bitrate
        value: 3000000-5000000

---

apiVersion: media.azure.upbound.io/v1beta2
kind: ServicesAccount
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta2/servicesaccountfilter
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    storageAccount:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      isPrimary: true

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta2/servicesaccountfilter
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: storage.azure.upbound.io/v1beta2
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta2/servicesaccountfilter
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountReplicationType: GRS
    accountTier: Standard
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
