# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: media.azure.upbound.io/v1beta1
kind: ServicesAccountFilter
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta1/serviceaccountfilter
  labels:
    testing.upbound.io/example-name: exampleservaccountfilter
  name: exampleservaccountfilter
spec:
  forProvider:
    mediaServicesAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: servaccountfiltermacc
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: servaccountfilter-rg
    firstQualityBitrate: 128000
    presentationTimeRange:
    - endInUnits: 15
      forceEnd: false
      liveBackoffInUnits: 0
      presentationWindowInUnits: 90
      startInUnits: 0
      unitTimescaleInMilliseconds: 1000
    trackSelection:
    - condition:
      - operation: Equal
        property: Type
        value: Audio
      - operation: NotEqual
        property: Language
        value: en
      - operation: NotEqual
        property: FourCC
        value: EC-3
    - condition:
      - operation: Equal
        property: Type
        value: Video
      - operation: Equal
        property: Bitrate
        value: 3000000-5000000

---

apiVersion: media.azure.upbound.io/v1beta1
kind: ServicesAccount
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta1/serviceaccountfilter
  labels:
    testing.upbound.io/example-name: servaccountfiltermacc
  name: servaccountfiltermacc
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: servaccountfilter-rg
    storageAccount:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: servaccountfiltersacc
      isPrimary: true

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta1/serviceaccountfilter
  labels:
    testing.upbound.io/example-name: servaccountfilter-rg
  name: servaccountfilter-rg
spec:
  forProvider:
    location: West Europe

---

apiVersion: storage.azure.upbound.io/v1beta1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: media/v1beta1/serviceaccountfilter
  labels:
    testing.upbound.io/example-name: servaccountfiltersacc
  name: servaccountfiltersacc
spec:
  forProvider:
    accountReplicationType: GRS
    accountTier: Standard
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: servaccountfilter-rg
