# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: dbformysql.azure.upbound.io/v1beta1
kind: VirtualNetworkRule
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "The resource depends on a Server and it needs a manual intervention."
  name: example
spec:
  forProvider:
    resourceGroupNameRef:
      name: example
    serverNameRef:
      name: example
    subnetIdRef:
      name: example
