apiVersion: eventhub.azure.upbound.io/v1beta1
kind: AuthorizationRule
metadata:
  annotations:
    meta.upbound.io/example-id: eventhub/v1beta1/authorizationrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    eventhubNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    listen: true
    manage: false
    namespaceNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    send: false

---

apiVersion: eventhub.azure.upbound.io/v1beta2
kind: EventHub
metadata:
  annotations:
    meta.upbound.io/example-id: eventhub/v1beta1/authorizationrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    messageRetention: 2
    namespaceNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    partitionCount: 2
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: eventhub.azure.upbound.io/v1beta2
kind: EventHubNamespace
metadata:
  annotations:
    meta.upbound.io/example-id: eventhub/v1beta1/authorizationrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    capacity: 2
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sku: Basic
    tags:
      environment: Production

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: eventhub/v1beta1/authorizationrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
