# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: labservices.azure.upbound.io/v1beta1
kind: LabServiceLab
metadata:
  annotations:
    meta.upbound.io/example-id: labservices/v1beta1/labserviceslab
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: labserviceslab-rg
    location: West Europe
    security: 
    - openAccessEnabled: true
    title: Test label
    connectionSetting:
    - clientSshAccess: Public
      clientRdpAccess: Public
    virtualMachine:
    - adminUser:
      - username: user 
        passwordSecretRef:
          key: example-key
          name: example-secret
          namespace: upbound-system
      imageReference: 
      - offer: 0001-com-ubuntu-server-focal
        publisher: canonical
        sku: 20_04-lts
        version: latest
      sku:
      - name: Classic_Fsv2_2_4GB_128_S_SSD
        capacity: 0

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: labservices/v1beta1/labserviceslab
  labels:
    testing.upbound.io/example-name: labserviceslab-rg
  name: labserviceslab-rg
spec:
  forProvider:
    location: West Europe

---

apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: upbound-system
type: Opaque
data:
  example-key: VGVyckFmb3JtMTIzIQ==
