# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesClusterNodePool
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    kubernetesClusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    nodeCount: 1
    tags:
      Environment: Production
    vmSize: Standard_DS2_v2

---

apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    defaultNodePool:
    - name: default
      nodeCount: 1
      vmSize: Standard_D2_v2
    dnsPrefix: exampleaks1
    identity:
    - type: SystemAssigned
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example-containerservice
    tags:
      Environment: Production
    apiServerAccessProfile:
      - authorizedIpRanges:
         - 192.168.1.0/24

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  labels:
    testing.upbound.io/example-name: example-containerservice
  name: example-containerservice-${Rand.RFC1123Subdomain}
spec:
  forProvider:
    location: West Europe
