apiVersion: containerregistry.azure.upbound.io/v1beta1
kind: AgentPool
metadata:
  annotations:
    meta.upbound.io/example-id: containerregistry/v1beta1/agentpool
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    containerRegistryNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: containerregistry.azure.upbound.io/v1beta2
kind: Registry
metadata:
  annotations:
    meta.upbound.io/example-id: containerregistry/v1beta1/agentpool
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europ
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sku: Premium

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: containerregistry/v1beta1/agentpool
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europ
