apiVersion: apimanagement.azure.upbound.io/v1beta2
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: apimanagement/v1beta2/backend
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    apiManagementNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    protocol: http
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    url: https://backend

---

apiVersion: apimanagement.azure.upbound.io/v1beta2
kind: Management
metadata:
  annotations:
    meta.upbound.io/example-id: apimanagement/v1beta2/backend
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    publisherEmail: company@terraform.io
    publisherName: My Company
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: Developer_1

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: apimanagement/v1beta2/backend
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
