# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: logz.azure.upbound.io/v1beta1
kind: TagRule
metadata:
  annotations:
    meta.upbound.io/example-id: logz/v1beta1/tagrule
  labels:
    testing.upbound.io/example-name: exampletagrule
  name: exampletagrule
spec:
  forProvider:
    logzMonitorIdSelector:
      matchLabels:
        testing.upbound.io/example-name: examplemonitor
    sendAadLogs: true
    sendActivityLogs: true
    sendSubscriptionLogs: true
    tagFilter:
    - action: Include
      name: name1
      value: value1
    - action: Exclude
      name: name2
      value: value2
---
apiVersion: logz.azure.upbound.io/v1beta1
kind: Monitor
metadata:
  annotations:
    meta.upbound.io/example-id: logz/v1beta1/tagrule
  labels:
    testing.upbound.io/example-name: examplemonitor
  name: ${Rand.RFC1123Subdomain}
spec:
  forProvider:
    location: West Europe
    plan:
    - billingCycle: MONTHLY
      effectiveDate: "2022-06-06T00:00:00Z"
      usageType: COMMITTED
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: rgtagrule
    user:
    - email: user@example.com
      firstName: Example
      lastName: User
      phoneNumber: "+12313803556"
---
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: logz/v1beta1/tagrule
  labels:
    testing.upbound.io/example-name: rgtagrule
  name: rgtagrule
spec:
  forProvider:
    location: West Europe
