# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: network.azure.upbound.io/v1beta1
kind: PrivateDNSZoneVirtualNetworkLink
metadata:
  name: example
spec:
  forProvider:
    privateDnsZoneNameRef:
      name: example
    resourceGroupNameRef:
      name: example
    virtualNetworkIdRef:
      name: example
