# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: network.azure.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: example
spec:
  forProvider:
    disableBgpRoutePropagation: false
    location: West Europe
    resourceGroupNameRef:
      name: example
    route:
    - addressPrefix: 10.1.0.0/16
      name: route1
      nextHopType: VnetLocal
    tags:
      environment: Production
