apiVersion: securityinsights.azure.upbound.io/v1beta1
kind: SentinelAlertRuleFusion
metadata:
  annotations:
    meta.upbound.io/example-id: securityinsights/v1beta1/sentinelalertrulefusion
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    alertRuleTemplateGuid: f71aba3d-28fb-450b-b192-4e76a83015c8
    logAnalyticsWorkspaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: example-fusion-alert-rule

---

apiVersion: operationsmanagement.azure.upbound.io/v1beta2
kind: LogAnalyticsSolution
metadata:
  annotations:
    meta.upbound.io/example-id: securityinsights/v1beta1/sentinelalertrulefusion
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    plan:
    - product: OMSGallery/SecurityInsights
      publisher: Microsoft
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    solutionName: SecurityInsights
    workspaceNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    workspaceResourceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: operationalinsights.azure.upbound.io/v1beta2
kind: Workspace
metadata:
  annotations:
    meta.upbound.io/example-id: securityinsights/v1beta1/sentinelalertrulefusion
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sku: PerGB2018

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: securityinsights/v1beta1/sentinelalertrulefusion
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
