apiVersion: securityinsights.azure.upbound.io/v1beta1
kind: SentinelAlertRuleMSSecurityIncident
metadata:
  annotations:
    meta.upbound.io/example-id: securityinsights/v1beta1/sentinelalertrulemssecurityincident
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    displayName: example rule
    logAnalyticsWorkspaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    productFilter: Microsoft Cloud App Security
    severityFilter:
    - High

---

apiVersion: operationalinsights.azure.upbound.io/v1beta2
kind: Workspace
metadata:
  annotations:
    meta.upbound.io/example-id: securityinsights/v1beta1/sentinelalertrulemssecurityincident
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sku: PerGB2018

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: securityinsights/v1beta1/sentinelalertrulemssecurityincident
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: securityinsights.azure.upbound.io/v1beta1
kind: SentinelLogAnalyticsWorkspaceOnboarding
metadata:
  annotations:
    meta.upbound.io/example-id: securityinsights/v1beta1/sentinelalertrulemssecurityincident
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    workspaceId: ${azurerm_log_analytics_workspace.example.id}
