apiVersion: securityinsights.azure.upbound.io/v1beta1
kind: SentinelAlertRuleMachineLearningBehaviorAnalytics
metadata:
  annotations:
    meta.upbound.io/example-id: securityinsights/v1beta1/sentinelalertrulemachinelearningbehavioranalytics
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    alertRuleTemplateGuid: 737a2ce1-70a3-4968-9e90-3e6aca836abf
    logAnalyticsWorkspaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: example-ml-alert-rule

---

apiVersion: operationalinsights.azure.upbound.io/v1beta2
kind: Workspace
metadata:
  annotations:
    meta.upbound.io/example-id: securityinsights/v1beta1/sentinelalertrulemachinelearningbehavioranalytics
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sku: PerGB2018

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: securityinsights/v1beta1/sentinelalertrulemachinelearningbehavioranalytics
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: securityinsights.azure.upbound.io/v1beta1
kind: SentinelLogAnalyticsWorkspaceOnboarding
metadata:
  annotations:
    meta.upbound.io/example-id: securityinsights/v1beta1/sentinelalertrulemachinelearningbehavioranalytics
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    workspaceId: ${azurerm_log_analytics_workspace.example.id}
