apiVersion: storage.azure.upbound.io/v1beta1
kind: Share
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/share
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    acl:
    - accessPolicy:
      - expiry: "2019-07-02T10:38:21.0000000Z"
        permissions: rwdl
        start: "2019-07-02T09:38:21.0000000Z"
      id: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI
    quota: 50
    storageAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/share
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: storage.azure.upbound.io/v1beta2
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/share
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountReplicationType: LRS
    accountTier: Standard
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
